const SOCKET_HOST_ADDRESS = process.env.REACT_APP_SOCKET_HOST_ADDRESS,
  SERVER_URL = process.env.REACT_APP_SERVER_URL,
  GET_JWT_TOKEN = "public/1.0/get-instant-token?id=",
  THREAD_LISTING = "public/1.0/get-channel-threads",
  MESSAGE_LISTING = "1.0/sms/get-conversation-last-msg",
  ASSIGN_CHAT = "1.0/thread/update-livechat-thread",
  SEND_MESSAGE = "1.0/sms/reply",
  FETCH_SINGLE_THREAD = "1.0/thread/get-sms-thread-by-id",
  UPDATE_THREAD = "1.0/thread/update-thread",
  UPDATE_LIVECHAT_THREAD = "1.0/thread/update-livechat-thread",
  Fetch_LIVECHAT_MESSAGES = "1.0/thread/get-thread-by-crm-id",
  DELETE_THREAD = "1.0/thread/delete-thread",
  DELETE_CRM_THREAD = "1.0/thread/delete-crm-threads",
  // SOCKET EVENTS
  FETCH_SMS_EVENT = "smsMessages",
  FETCH_LIVECHAT_MESSAGES_EVENT = "livechat-message",
  REPLAYTO_LIVECHAT_MESSAGES_EVENT = "livechat-message",
  JOIN_BUDDY_CHATROOM_EVENT = "buddychat-joinRoom",
  LIVECHAT_THREAD_UPDATE_EVENT = "alivechat-threadUpdate",
  BUDDYCHAT_TYPING_EVENT = "buddychat-message-typing",
  SMS_THREAD_UPDATE_EVENT = "updatedThreadEvent",
  UPATE_THREAD_CRM_EVENT = "updatedThreadCrmEvent";
  


export {
  SOCKET_HOST_ADDRESS,
  SERVER_URL,
  GET_JWT_TOKEN,
  THREAD_LISTING,
  MESSAGE_LISTING,
  ASSIGN_CHAT,
  SEND_MESSAGE,
  FETCH_SINGLE_THREAD,
  UPDATE_THREAD,
  UPDATE_LIVECHAT_THREAD,
  Fetch_LIVECHAT_MESSAGES,
  DELETE_THREAD,
  DELETE_CRM_THREAD,
  SMS_THREAD_UPDATE_EVENT,
  UPATE_THREAD_CRM_EVENT,
  FETCH_SMS_EVENT,
  FETCH_LIVECHAT_MESSAGES_EVENT,
  REPLAYTO_LIVECHAT_MESSAGES_EVENT,
  JOIN_BUDDY_CHATROOM_EVENT,
  LIVECHAT_THREAD_UPDATE_EVENT,
  BUDDYCHAT_TYPING_EVENT,
};
